# Generated by Django 4.0.3 on 2022-04-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recado',
            name='texto',
            field=models.TextField(default='*'),
        ),
    ]
